### ISSUE TITLE
Gaslands Refuelled

### ISSUE THREAD

**Issue by bfncs** [voidstate/gaslandsgarage#10]
Thanks for making this awesome tool! It would be amazing if it would work with all the changes in Gaslands Refuelled:

https://gaslands.com/whats-changed-in-refuelled/
https://www.reddit.com/r/gaslandsplayers/comments/d5si11/gaslands_refueled_technical_changelog/

Have you been thinking about an update? If yes, do you plan to support old and new roles in parallel or replacing old by new?

**Comment by voidstate** [comment]
I’m afraid I’ve moved on from Gaslands now. I’ll leave this app up until the domain expires but then it’ll disappear. 

...unless someone wants to take it over?

**Comment by bfncs** [comment]
Thanks for answering and building this great tool. I started working on something similar using React & TypeScript as I'm more familiar with it, but this is still lacking most of the features: https://github.com/bfncs/gaslands-builder
